[tool.poetry]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Perfect Intel Bot"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.13.2"
discord.py = "^2.7.0"
flask = "^2.3.3"

[tool.poetry.dev-dependencies]
