[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Perfect Intel Bot"
requires-python = ">=3.11"

dependencies = [
    "aiohttp>=3.13.2",
    "discord-py>=2.6.4",
    "Flask>=2.3.3",
]
